name: Video Downloader

on:
  workflow_dispatch:  # Jalankan manual di GitHub Actions

jobs:
  download-video:
    runs-on: ubuntu-latest  # Gunakan OS Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Ambil kode dari repo

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Gunakan Python 3.12

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -U yt-dlp  # Pastikan yt-dlp terbaru

      - name: Run Video Downloader
        run: python url4.py "https://www.eporner.com/video-60QyIjr4TpG/savannah-b-hot-milf-pawg-in-fishnet-pantyhose-ll-poison-your-mind-he-busted-right-on-her-thick-ass/"

      - name: Upload Video
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-video
          path: "*.mp4"  # Simpan video yang diunduh
