name: test

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-22.04
    steps:
      - name: Install tmate
        run: |
          sudo apt-get update
          sudo apt-get install -y tmate

      - name: install gcc
        run: sudo apt update && sudo apt install -y wget gcc g++ gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

      - name: Install zip utility
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: dowload source
        run: git clone https://github.com/alqix/android_kernel_xiaomi_mt6877.git kernel
             cd kernel
             wget -O clang.tar.xz https://github.com/Gonon-Kernel/gonon-clang/releases/download/16.0.6-20231104-release/GononClang-16.0.6-20231104.tar.xz
             tar -xvJf clang.tar.xz

      - name: Start tmate session
        run: |
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready

      - name: Show SSH info
        run: |
          echo "SSH Command:"
          tmate -S /tmp/tmate.sock display -p "#{tmate_ssh}"
          echo "Web Terminal:"
          tmate -S /tmp/tmate.sock display -p "#{tmate_web}"

      - name: KEEP SESSION ALIVE
        run: |
          echo "Tmate active. Workflow will NOT stop."
          sleep infinity
