name: transcribe

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Masukkan URL video'
        required: true
        type: string
      nama_video:
        description: 'Nama file video (contoh: video)'
        required: true
        type: string
      nama_model:
        description: 'Pilih model Whisper'
        required: true
        default: "base.en"
        type: choice
        options:
          - tiny
          - tiny.en
          - base
          - base.en
          - small
          - small.en
          - medium
          - medium.en
          - large
          - turbo
      send_to_telegram:
        description: "Whatever send to telegram ci channel or not"
        required: true
        type: choice
        default: "true"
        options:
          - "true"
          - "false"
      send_to_telegram:
        description: "send to github realese or not"
        required: true
        type: choice
        default: "false"
        options:
          - "true"
          - "false"

jobs:
  transcribe:
    runs-on: ubuntu-22.04

    steps:
      - name: Download video & convert to wav
        run: |
          mkdir kernel
          sudo apt-get install -y ffmpeg
          cd kernel
          curl -L "${{ github.event.inputs.video_url }}" -o "${{ github.event.inputs.nama_video }}".mp4
          ffmpeg -y -i "${{ github.event.inputs.nama_video }}".mp4 \
            -ar 16000 -ac 1 -c:a pcm_s16le audio.wav

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg cmake git python3-pip
          pip install -U yt-dlp
          pip install -U openai-whisper
          pip install setuptools-rust
          
      - name: Set start time
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV

      - name: Transcribe to SRT
        run: |
          cd kernel
          whisper \
            audio.wav \
            --model ${{ github.event.inputs.nama_model }} \
            --language en \
            --output_format srt
            
      - name: Calculate duration
        run: |
          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))
          echo "DURATION_SECONDS=$DURATION" >> $GITHUB_ENV
      
      - name: Format duration
        run: |
          M=$((DURATION_SECONDS / 60))
          S=$((DURATION_SECONDS % 60))
          echo "DURATION_FORMAT=${M}m ${S}s" >> $GITHUB_ENV
          
      - name: Format build date
        run: |
          TZ=Asia/Jakarta date '+%d-%m-%Y %H:%M:%S WIB'
          echo "BUILD_DATE=$(TZ=Asia/Jakarta date '+%d-%m-%Y %H:%M:%S WIB')" >> $GITHUB_ENV
            
      - name: mv
        run: |
          cd kernel
          mv *.srt  "${{ github.event.inputs.nama_video }}".srt

      - name: Generate tag
        id: tag
        run: |
          echo "TAG=auto-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Upload SRT to TELEGRAM
        uses: xz-dev/TelegramFileUploader@v1.1.1
        if: ${{ always() && github.event.inputs.send_to_telegram == 'true' }}
        with:
          to-who: '${{ secrets.TELEGRAM_API_TO_WHO }}'
          message: |
            #whisperopenai #Andromax

            ⚙️ **Build Infomation:**
            - build succesfuly by **Whisper Open Ai**
            
            - subtitle name : ${{ github.event.inputs.nama_video }}.srt
            
            - whisper model : 📊 **${{ github.event.inputs.nama_model }}**
            
            - Build Duration : 🕐 **${{ env.DURATION_FORMAT }}**
            
            - date : 📅 **${{ env.BUILD_DATE }}**
          files: kernel/${{ github.event.inputs.nama_video }}.srt
        env:
          API_ID: ${{ secrets.TELEGRAM_API_ID }}
          API_HASH: ${{ secrets.TELEGRAM_API_HASH }}
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          
      - name: Upload SRT to Release
        uses: softprops/action-gh-release@v1
        if: ${{ always() && github.event.inputs.send_to_github == 'true' }}
        with:
          tag_name: ${{ steps.tag.outputs.TAG }}
          name: "Transcription ${{ steps.tag.outputs.TAG }}"
          files: kernel/*.srt
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
